---
- hosts: all 
  become: yes
  tasks:
    - name: Install package GO
      package:
        name: go
        state: latest

    - name: Install package GIT
      package:
        name: git
        state: latest

    - name: Enable service sshd
      ansible.builtin.service:
        name: sshd.service
        enabled: yes

    - name : Install Make package
      package:
        name: make 
        state: latest
     
    - name: Create new service in systemd
      ansible.builtin.template:
        src: template/golang.service
        dest: /etc/systemd/system/golang.service
        
    - name: Create go directory
      ansible.builtin.file:
        path: /tmp/golangapp
        state: directory
        mode: '0755'

    - name: Get goland myip from distant git
      ansible.builtin.git:
        repo: https://github.com/BastienBalaud/golang-myip.git
        dest: /tmp/golangapp/
        clone: yes
        update: yes

    - name: Restart systemd daemon to read new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Set selinux in permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive 

    - name: Makefile with shell
      shell: 'make -C /tmp/golangapp -f /tmp/golangapp/Makefile'
      args:
        executable: /bin/bash
      become: True

    - name: Start service golang
      ansible.builtin.service:
        name: golang.service
        state: started

    - name: Enable service golang
      ansible.builtin.service:
        name: golang.service
        enabled: yes

    - name: Open port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

##ADD ANOTHER SSH KEY FOR ANOTHER USER

    - name: Create new user
      ansible.builtin.user: 
        name: 'correcteur'
        home: '/home/correcteur/'
     
    - name: New .SSH Directory for new user
      file:
        path: /home/correcteur/.ssh
        state: directory
        owner: correcteur
        mode: '0755'

    - name: Adding new key for new user
      shell: 'curl https://github.com/BastienBalaud.keys > /home/correcteur/.ssh/authorized_keys'
      become: True 
